### ISSUE TITLE
Repository name confusing

### ISSUE THREAD

**Issue by gidsi** [SpaceApi/directory-api#4]
I would like to rename the repository, right now the name is confusing to everyone not involved in the project.
The application scraps the directory, checks all spaces and serves the reachable and valid formated in a more programmable friendly manner.

**Comment by gidsi** [comment]
i would suggest "directory-api" or something similar.

**Comment by dbrgn** [comment]
:+1: "directory-api" sounds good to me.

**Comment by rnestler** [comment]
Maybe even add a -go postfix so it is clear that it is a go implementation. So "directory-api-go".

**Comment by gidsi** [comment]
> Maybe even add a -go postfix so it is clear that it is a go implementation. So "directory-api-go".

I wouldn't add the language, it's already visible in the list and in the top bar.
As long as we don't have another implementation in another language i wouldn't add it :)

**Comment by gidsi** [comment]
renamed to `directory-api`
